modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "AGPL v3"

[[mods]]
modId = "trainutilities"
version = "${version}"
displayName = "Create: TrainUtilities"
authors = "Adeptstack"
description = '''
---
'''
#logoFile = ""

[[dependencies.trainutilities]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trainutilities]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.trainutilities]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,]"
ordering="NONE"
side="BOTH"